[package]
name = "tenebra-node"
description = "Tenebra L1 node: ABCI 2.0 application for CometBFT, devnet setup and a CLI wallet."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "tenebra-node"
path = "src/main.rs"

[dependencies]
tenebra-chain.workspace = true
tendermint-abci = "0.40.4"
tendermint-proto = "0.40.4"
ed25519-dalek.workspace = true
getrandom.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json.workspace = true
sha2 = "0.10"
base64 = "0.22"

[lints]
workspace = true
